baseURL = "https://migueluza.github.io/data-plane"
languageCode = "es"
title = "Data Plane"
theme = "data-plane"
paginate = "2"
publishDir = "docs"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Homepage"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "services"
    name = "Services"
    title = "Services Section"
    url = "/services/"
    weight = 2
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    title = "Resources Section"
    url = "/resources/"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "contact section"
    url = "/contact/"
    weight = 4
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog Section"
    url = "/blog/"
    parent = "resources"
    weight = 1
  [[menu.main]]
    identifier = "webinar-events"
    name = "Webinar & Events"
    title = "Webinar&Events Section"
    url = "/webinar-events/"
    parent = "resources"
    weight = 2
[params]
  dateFormat = "Jan 2, 2006"
[taxonomies]
  tag = "tags"
